bot:
  name: "My AI bot!"
  token: "my_bot_token_keep_secret"
  ownerId: "580050773522513920"
maxEntriesPerOwner: 1
hostConstraints:
  maxSimultaneousMakeRequests: 1
  totalImagesInMakeCommand: 4
timeouts:
  imageNotAppearing: 10
  imageNotUpdating: 10
grpcServer:
  host: "localhost"
  port: 51001
imagesFolder: "/app"